### PR TITLE
Add example Dockerfile to build environment from yaml file

### PR DESCRIPTION
**Pull request by mbjoseph**
This copies the environment.yml file into the build, creates the environment, deletes the environment.yml file, then installs `nb_conda_kernels` to make the environment appear as a kernel. Not sure whether this last part will play well with Jupyter Hub, or whether there is a better solution.

### CODE REVIEW

**Comment by mbjoseph** [comment]
Have a look see @lwasser!

The build process locally is:

```bash
cd earth-analytics-binder
docker build -t earthlab/earth-analytics .
docker run -it -p 8888:8888 earthlab/earth-analytics
```

**Comment by lwasser** [comment]
@mbjoseph nb_conda kernels should be in the EA envt! is it not there? Perhaps this is the wrong yaml file or i need to update it!

**Comment by lwasser** [comment]
i'm sorry that i missed this PR. i need to check my new email folders. i was wondering how this process was going.

**Comment by mbjoseph** [comment]
Ok - so I just tried building without install nb_conda_kernels explicitly (using the new environment.yml file), and this environment doesn't show up. 

@lwasser do you know whether nb_conda_kernels needs to be installed in the "base" conda environment to have access to other environments when launching a notebook?

**Comment by lwasser** [comment]
so this is the weirdness @mbjoseph on my computer, if you activate the earth-analytics-envt at the command line and launch jupyter from that terminal window the envt is there. but you don't "see it" as a name in the kernel list but it works. this hasn't worked on everyone's computers however so i added the nb_kernel to the yaml file. the problem is i din't add it here - so i just added it to the yaml file a bit ago!! the envt doesn't show up unless you do this. but it does work on some computers without it just not all (which is no good!). make sense?

**Comment by lwasser** [comment]
so now i'll be curious to see if binder breaks with the docker file in here. gonna merge this.

**Comment by lwasser** [comment]
so we might not need 
```
# to have environments show up as kernels
RUN conda install --channel=conda-forge nb_conda_kernels
``` 
with it in the yaml file? what do you think @mbjoseph  ??
Also so how do we get this file over to dockerhub? is that a CI step?

**Comment by mbjoseph** [comment]
"if you activate the earth-analytics-envt at the command line and launch jupyter from that terminal window the envt is there" 

^ That makes sense, because the notebook is being launched from that environment. I think the default for the scipy image is to launch the notebook from the "base" conda environment, rather than a custom environment, and I don't think we want to mess with how notebooks etc. get launched to avoid breaking compatibility with Jupyter Hub. 

I think we do need to install nb_conda_kernels in the "base" environment. It does not work for me when it's only installed in the earthlab environment. 

Automated builds have to be set up from Docker Hub: https://docs.docker.com/docker-hub/builds/
I'd be happy to do this if you want, or walk you through it, or you can do it if you want!

**Comment by mbjoseph** [comment]
Or, maybe we can just install all of your deps into the base environment and not worry about multiple environments...

**Comment by lwasser** [comment]
cool thanks!

we DO want jupyter hub to launch using the EA envt as the default. That is how it works for something like coursera or something when they have an envt configured. you dont want to make your user "pick" the envt. Thus... when you launch jupyter hub, you do it using the envt ideally. i know this has been setup before and i'd like to try to set it up this way!!

I can talk with chris more about it too but what happens if the docker file runs 
source activate earth-analytics-python and then launches?

**Comment by lwasser** [comment]
i'm ok with that option too @mbjoseph  (installing everything into the base) the key is that we have everything we need in one place that is the default place

**Comment by lwasser** [comment]
the conda envt allows a user to manage multiple installations. So for a user you wouldn't want to mess with the base envt on their computer potentially!! but for docker sure - we can update the base and use that. i'm cool with that.

**Pull request merged**
